[project]
name = "student-report-card-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fpdf2>=2.8.2",
    "streamlit>=1.43.1",
]
