[project]
name = "build-data-driven-python-web-apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.44.1",
    "streamlit-extras>=0.6.0",
]
